package com.imysko.testtaskvk.utils

object TestTags {

    const val PRODUCT_CARD = "PRODUCT_CARD"
    const val PRODUCT_CARD_PRICE = "PRODUCT_CARD_PRICE"
    const val PRODUCT_CARD_DISCOUNT_PRICE = "PRODUCT_CARD_DISCOUNT_PRICE"
    const val PRODUCT_CARD_OUT_STOCK = "PRODUCT_CARD_OUT_STOCK"

    const val PRODUCTS_LIST = "PRODUCTS_LIST"
    const val PRODUCTS_LIST_ON_LOADING = "PRODUCTS_LIST_ON_LOADING"
    const val PRODUCTS_LIST_NOT_FOUND = "PRODUCTS_LIST_NOT_FOUND"
    const val PRODUCTS_LIST_ON_ERROR = "PRODUCTS_LIST_ON_ERROR"
    const val PRODUCTS_LIST_NO_INTERNET_CONNECTION = "PRODUCTS_LIST_NO_INTERNET_CONNECTION"
}
